# Generated by Django 3.0.5 on 2020-04-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSSapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='rss_urls',
            name='title',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
