# Generated by Django 3.0.6 on 2020-06-07 08:54

from django.db import models, migrations


def add_urls(apps, schema_editor):
    RSS_URLS = apps.get_model('RSSapp', 'RSS_URLS')
    url0 = RSS_URLS(id=0, url='https://medium.com/feed/topic/artificial-intelligence', title='Handpicked stories about Artificial Intelligence on Medium')
    url0.save()
    url1 = RSS_URLS(id=1, url='https://stackoverflow.com/feeds', title='Recent Questions - Stack Overflow')
    url1.save()
    url2 = RSS_URLS(id=2, url='https://www.djangoproject.com/rss/weblog/', title='The Django weblog')
    url2.save()
    url3 = RSS_URLS(id=3, url='https://nu.nl/rss', title='NU')
    url3.save()
    url4 = RSS_URLS(id=4, url='https://medium.com/feed/topic/machine-learning', title='Handpicked stories about Machine Learning on Medium')
    url4.save()
    url5 = RSS_URLS(id=5, url='https://www.youtube.com/feeds/videos.xml?channel_id=UCgtOMaHBiYvsRYZ77utf8FQ', title='YouTube: Eric Karlsson Bouldering')
    url5.save()
    url6 = RSS_URLS(id=6, url='https://www.youtube.com/feeds/videos.xml?channel_id=UC3SktmgWisLKBTVP4cARRZw', title='YouTube: Andrew MacFarlane')
    url6.save()
    url7 = RSS_URLS(id=7, url='https://www.youtube.com/feeds/videos.xml?channel_id=UCaQ7laUNRnsAwk6KbPwtJIg', title='YouTube: Jenn Sends')
    url7.save()
    url8 = RSS_URLS(id=8, url='https://www.youtube.com/feeds/videos.xml?channel_id=UCpExuV8qJMfCaSQNL1YG6bQ', title='YouTube: Better Than Yesterday')
    url8.save()


class Migration(migrations.Migration):

    dependencies = [
        ('RSSapp', '0002_auto_20200428_1849'),
    ]

    operations = [
        migrations.RunPython(add_urls),
    ]
